package com.phloc.html.hc.html;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

import com.phloc.commons.text.IPredefinedLocaleTextProvider;
import com.phloc.html.hc.IHCNode;
import com.phloc.html.hc.IHCNodeBuilder;

/**
 * Represents an HTML &lt;DIV&gt; element<br>
 * This file is automatically generated from
 * com.phloc.html.supplementary.main.MainCreateHCClasses so DO NOT EDIT!
 * 
 * @author Philip Helger
 */
public class HCDiv extends AbstractHCDiv <HCDiv>
{
  /**
   * Create a new DIV element
   */
  public HCDiv ()
  {
    super ();
  }

  /**
   * Create a new DIV element with the passed child text
   * 
   * @param aChild
   *        The child text provider to be appended. May be <code>null</code>
   * @return The created HCDiv element and never <code>null</code>
   */
  @Nonnull
  public static HCDiv create (@Nullable final IPredefinedLocaleTextProvider aChild)
  {
    return new HCDiv ().addChild (aChild);
  }

  /**
   * Create a new DIV element with the passed child texts
   * 
   * @param aChildren
   *        The child texts to be appended. May be <code>null</code>
   * @return The created HCDiv element and never <code>null</code>
   */
  @Nonnull
  public static HCDiv create (@Nullable final IPredefinedLocaleTextProvider... aChildren)
  {
    return new HCDiv ().addChildren (aChildren);
  }

  /**
   * Create a new DIV element with the passed child text
   * 
   * @param sChild
   *        The child to be appended. May be <code>null</code>
   * @return The created HCDiv element and never <code>null</code>
   */
  @Nonnull
  public static HCDiv create (@Nullable final String sChild)
  {
    return new HCDiv ().addChild (sChild);
  }

  /**
   * Create a new DIV element with the passed child texts
   * 
   * @param aChildren
   *        The child texts to be appended. May be <code>null</code>
   * @return The created HCDiv element and never <code>null</code>
   */
  @Nonnull
  public static HCDiv create (@Nullable final String... aChildren)
  {
    return new HCDiv ().addChildren (aChildren);
  }

  /**
   * Create a new DIV element with the passed child node
   * 
   * @param aChild
   *        The child node to be appended. May be <code>null</code>
   * @return The created HCDiv element and never <code>null</code>
   */
  @Nonnull
  public static HCDiv create (@Nullable final IHCNodeBuilder aChild)
  {
    return new HCDiv ().addChild (aChild);
  }

  /**
   * Create a new DIV element with the passed child nodes
   * 
   * @param aChildren
   *        The child nodes to be appended. May be <code>null</code>
   * @return The created HCDiv element and never <code>null</code>
   */
  @Nonnull
  public static HCDiv create (@Nullable final IHCNodeBuilder... aChildren)
  {
    return new HCDiv ().addChildren (aChildren);
  }

  /**
   * Create a new DIV element with the passed child node
   * 
   * @param aChild
   *        The child node to be appended. May be <code>null</code>
   * @return The created HCDiv element and never <code>null</code>
   */
  @Nonnull
  public static HCDiv create (@Nullable final IHCNode aChild)
  {
    return new HCDiv ().addChild (aChild);
  }

  /**
   * Create a new DIV element with the passed child nodes
   * 
   * @param aChildren
   *        The child nodes to be appended. May be <code>null</code>
   * @return The created HCDiv element and never <code>null</code>
   */
  @Nonnull
  public static HCDiv create (@Nullable final IHCNode... aChildren)
  {
    return new HCDiv ().addChildren (aChildren);
  }

  /**
   * Create a new DIV element with the passed child nodes
   * 
   * @param aChildren
   *        The child nodes to be appended. May be <code>null</code>
   * @return The created HCDiv element and never <code>null</code>
   */
  @Nonnull
  public static HCDiv create (@Nullable final Iterable <? extends IHCNode> aChildren)
  {
    return new HCDiv ().addChildren (aChildren);
  }
}
