/**
 * Copyright (C) 2006-2012 phloc systems
 * http://www.phloc.com
 * office[at]phloc[dot]com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.phloc.html.hc.html;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;

import java.util.ArrayList;

import org.junit.Test;

import com.phloc.commons.collections.ContainerHelper;
import com.phloc.commons.text.IPredefinedLocaleTextProvider;
import com.phloc.html.hc.IHCNode;

/**
 * Test class for class {@link HCH3} This file is automatically generated from
 * com.phloc.html.tools.MainCreateHCClasses so DO NOT EDIT!
 * 
 * @author philip
 */
public final class HCH3Test
{
  @Test
  public void testCreate ()
  {
    assertFalse (new HCH3 ().hasChildren ());
    assertEquals (0, HCH3.create ((IPredefinedLocaleTextProvider) null).getChildCount ());
    assertEquals (0, HCH3.create ((IPredefinedLocaleTextProvider) null, (IPredefinedLocaleTextProvider) null)
                         .getChildCount ());
    assertEquals (1, HCH3.create ("Text").getChildCount ());
    assertEquals (0, HCH3.create ((String) null).getChildCount ());
    assertEquals (1, HCH3.create (HCB.create ("Bold")).getChildCount ());
    assertEquals (0, HCH3.create ((IHCNode) null).getChildCount ());
    assertEquals (3, HCH3.create ("Hallo", "Welt", "!!!").getChildCount ());
    assertEquals (0, HCH3.create (new String [0]).getChildCount ());
    assertEquals (0, HCH3.create ((String []) null).getChildCount ());
    assertEquals (2, HCH3.create (HCB.create ("Bold"), HCI.create ("Italic")).getChildCount ());
    assertEquals (0, HCH3.create (new IHCNode [0]).getChildCount ());
    assertEquals (0, HCH3.create ((IHCNode []) null).getChildCount ());
    assertEquals (2, HCH3.create (ContainerHelper.newList (HCB.create ("Bold"), HCI.create ("Italic")))
                         .getChildCount ());
    assertEquals (0, HCH3.create (new ArrayList <IHCNode> ()).getChildCount ());
  }

  @SuppressWarnings ("deprecation")
  @Test
  public void testDeprecated ()
  {
    assertFalse (new HCH3 ().hasChildren ());
    assertEquals (0, new HCH3 ((IPredefinedLocaleTextProvider) null).getChildCount ());
    assertEquals (1, new HCH3 ("Text").getChildCount ());
    assertEquals (0, new HCH3 ((String) null).getChildCount ());
    assertEquals (1, new HCH3 (HCB.create ("Bold")).getChildCount ());
    assertEquals (0, new HCH3 ((IHCNode) null).getChildCount ());
    assertEquals (3, new HCH3 ("Hallo", "Welt", "!!!").getChildCount ());
    assertEquals (0, new HCH3 (new String [0]).getChildCount ());
    assertEquals (0, new HCH3 ((String []) null).getChildCount ());
    assertEquals (2, new HCH3 (HCB.create ("Bold"), HCI.create ("Italic")).getChildCount ());
    assertEquals (0, new HCH3 (new IHCNode [0]).getChildCount ());
    assertEquals (0, new HCH3 ((IHCNode []) null).getChildCount ());
    assertEquals (2, new HCH3 (ContainerHelper.newList (HCB.create ("Bold"), HCI.create ("Italic"))).getChildCount ());
    assertEquals (0, new HCH3 (new ArrayList <IHCNode> ()).getChildCount ());
  }
}
